# Generated by Django 2.2.5 on 2019-09-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='board_cols',
            new_name='height',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='board_bombs',
            new_name='mines',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='board_rows',
            new_name='width',
        ),
    ]
