# Generated by Django 2.2.5 on 2019-09-17 21:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190917_1411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='board',
            new_name='board_mines',
        ),
        migrations.AddField(
            model_name='game',
            name='user_board',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
