# Generated by Django 2.2.5 on 2019-09-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190917_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('beg', 'beginner'), ('int', 'intermediate'), ('exp', 'expert'), ('cus', 'custom')], default='beg', max_length=3),
        ),
    ]
